Repository harsha-accenture/scheduler-jupyter-plugin, pull requests merged in 2025-02, with the labels that each got.

#19 Merge dev into vertex backend execution history branch
  .copier-answers.yml
  .github/workflows/binder-on-pr.yml
  .github/workflows/build.yml
  .github/workflows/check-release.yml
  .github/workflows/enforce-label.yml
  .github/workflows/prep-release.yml
  .github/workflows/publish-release.yml
  .github/workflows/update-integration-tests.yml
  .gitignore
  .prettierignore
  .yarnrc.yml
  CHANGELOG.md
  LICENSE
  README.md
  RELEASE.md
  babel.config.js
  binder/environment.yml
  binder/postBuild
  conftest.py
  install.json
  jest.config.js
  jupyter-config/server-config/scheduler_jupyter_plugin.json
  package.json
  pyproject.toml
  scheduler_jupyter_plugin/__init__.py
  scheduler_jupyter_plugin/commons/constants.py
  scheduler_jupyter_plugin/credentials.py
  scheduler_jupyter_plugin/handlers.py
  scheduler_jupyter_plugin/tests/__init__.py
  scheduler_jupyter_plugin/tests/test_handlers.py
  scheduler_jupyter_plugin/urls.py
  schema/plugin.json
  setup.py
  src/__tests__/scheduler_jupyter_plugin.spec.ts
  src/handler.ts
  src/index.ts
  style/base.css
  style/index.css
  style/index.js
  tsconfig.json
  tsconfig.test.json
  ui-tests/README.md
  ui-tests/jupyter_server_test_config.py
  ui-tests/package.json
  ui-tests/playwright.config.js
  ui-tests/tests/scheduler_jupyter_plugin.spec.ts
  ui-tests/yarn.lock
  yarn.lock
Labels: enhancement

#23 Create vertex scheduler UI implemented
  src/scheduler/NotebookScheduler.tsx
  src/scheduler/common/LearnMore.tsx
  src/scheduler/vertex/CreateVertexScheduler.tsx
  src/utils/Const.ts
Labels: enhancement

#9 Added code for backend API for listing drop-down values on create vertex scheduler page
  pyproject.toml
  scheduler_jupyter_plugin/commons/constants.py
  scheduler_jupyter_plugin/controllers/compute.py
  scheduler_jupyter_plugin/controllers/iam.py
  scheduler_jupyter_plugin/controllers/storage.py
  scheduler_jupyter_plugin/controllers/vertex.py
  scheduler_jupyter_plugin/handlers.py
  scheduler_jupyter_plugin/services/compute.py
  scheduler_jupyter_plugin/services/iam.py
  scheduler_jupyter_plugin/services/storage.py
  scheduler_jupyter_plugin/services/vertex.py
Labels: enhancement

#12 Added code for backend APIs for create schedule and bucket
  pyproject.toml
  scheduler_jupyter_plugin/controllers/vertex.py
  scheduler_jupyter_plugin/handlers.py
  scheduler_jupyter_plugin/models/models.py
  scheduler_jupyter_plugin/services/vertex.py
Labels: enhancement

#16 Added backend code for APIs for listing screen
  scheduler_jupyter_plugin/controllers/vertex.py
  scheduler_jupyter_plugin/handlers.py
  scheduler_jupyter_plugin/models/models.py
  scheduler_jupyter_plugin/services/vertex.py
Labels: enhancement

#20 Added backend code for APIs for vertex execution history page
  pyproject.toml
  scheduler_jupyter_plugin/controllers/logEntries.py
  scheduler_jupyter_plugin/controllers/storage.py
  scheduler_jupyter_plugin/controllers/vertex.py
  scheduler_jupyter_plugin/handlers.py
  scheduler_jupyter_plugin/services/logEntries.py
  scheduler_jupyter_plugin/services/storage.py
  scheduler_jupyter_plugin/services/vertex.py
Labels: enhancement

#29 Implemented Vertex schedule listing
  src/scheduler/NotebookScheduler.tsx
  src/scheduler/vertex/CreateVertexScheduler.tsx
  src/scheduler/vertex/ListVertexScheduler.tsx
  src/scheduler/vertex/VertexInterfaces.ts
  src/scheduler/vertex/VertexScheduleJobs.tsx
  src/services/Vertex.tsx
  src/utils/Config.ts
  src/utils/Icons.tsx
  style/cluster.css
  style/icons/list_active_icon.svg
  style/icons/list_completed_with_error.svg
  style/icons/list_error_icon.svg
  style/icons/list_pause_icon.svg
  style/icons/scheduler_edit_calendar copy.svg
  style/icons/scheduler_edit_dag copy.svg
  style/icons/scheduler_pause copy.svg
  style/icons/scheduler_play copy.svg
  style/index.css
Labels: enhancement

#30 Execution history for vertex
  src/scheduler/NotebookScheduler.tsx
  src/scheduler/vertex/CreateVertexScheduler.tsx
  src/scheduler/vertex/ListVertexScheduler.tsx
  src/scheduler/vertex/VertexExecutionHistory.tsx
  src/scheduler/vertex/VertexInterfaces.ts
  src/scheduler/vertex/VertexJobRuns.tsx
  src/scheduler/vertex/VertexJobTaskLogs.tsx
  src/scheduler/vertex/VertexScheduleJobs.tsx
  src/services/LogEntries.tsx
  src/services/Storage.tsx
  src/services/Vertex.tsx
  src/utils/Icons.tsx
  style/icons/cluster_icon copy.svg
  style/icons/create_cluster_icon.svg
  style/icons/google-cloud copy.svg
  style/icons/scheduler_edit_calendar copy.svg
  style/icons/scheduler_edit_dag copy.svg
  style/icons/scheduler_pause copy.svg
  style/icons/scheduler_play copy.svg
  style/icons/signin_google_icon copy.svg
  style/notebookScheduler.css
Labels: enhancement

#32 Vertex schedule listing UI frontend CSS change
  style/notebookScheduler.css
Labels: enhancement

#33 CSS fixed in execution history task log
  src/scheduler/vertex/VertexJobTaskLogs.tsx
  style/notebookScheduler.css
Labels: enhancement

#34 Back arrow button aligment fixed
  style/notebookScheduler.css
Labels: enhancement

#35 Resolved issue: Edit schedule functionality is not working for the composer.
  scheduler_jupyter_plugin/services/airflow.py
Labels: bug

#36 Changed the label in template file to scheduler-jupyter-plugin
  scheduler_jupyter_plugin/dagTemplates/pysparkJobTemplate-v1.txt
  src/login/ConfigSelection.tsx
Labels: bug

#40 Duplicate error message showing for cluster and serverless is fixed in composer
  src/scheduler/composer/CreateNotebookScheduler.tsx
Labels: bug

#42 Handled 403 error code in env list api
  scheduler_jupyter_plugin/services/composer.py
Labels: enhancement

#43 Resolved issue while error handling
  scheduler_jupyter_plugin/services/composer.py
Labels: enhancement

#44 Handled 403 error in ui config api
  scheduler_jupyter_plugin/services/vertex.py
Labels: enhancement

#45 Handled 403 error in List Schedules API
  scheduler_jupyter_plugin/services/vertex.py
Labels: enhancement

#41 Implemented error text below environment dropdown to notify composer API is disabled followed by a link to enable it.
  src/index.ts
  src/scheduler/common/EnableNotifyMessage.tsx
  src/scheduler/composer/CreateNotebookScheduler.tsx
  src/scheduler/composer/ListNotebookScheduler.tsx
  src/services/SchedulerServices.ts
  src/utils/Config.ts
  style/notebookScheduler.css
  style/submitJob.css
Labels: enhancement

#46 Fixed issues with create new bucket
  src/scheduler/vertex/CreateVertexScheduler.tsx
  src/scheduler/vertex/VertexJobTaskLogs.tsx
  src/services/Storage.tsx
  src/utils/Const.ts
Labels: bug

#47 Toast message changed for issue #399127616 to help recognize downloa…
  src/services/Storage.tsx
Labels: enhancement, good first issue

#50 License updated
  LICENSE
  third-party-licenses.txt
Labels: enhancement

#48 Accelerator Type and accelerated count field in create vertex form made to optional
  src/scheduler/vertex/CreateVertexScheduler.tsx
Labels: enhancement

#51 Added license in some files where missing
  babel.config.js
  conftest.py
  contributing.md
  jest.config.js
  scheduler_jupyter_plugin/tests/__init__.py
  setup.py
  src/__tests__/scheduler_jupyter_plugin.spec.ts
  src/controls/DynamicDropdown.tsx
  src/controls/RegionDropdown.tsx
  src/controls/SchedulerWidget.tsx
  src/services/LoggingService.ts
  style/index.js
  ui-tests/jupyter_server_test_config.py
  ui-tests/playwright.config.js
  ui-tests/tests/scheduler_jupyter_plugin.spec.ts
Labels: enhancement

#52 Updating dev branch from main
  babel.config.js
  conftest.py
  contributing.md
  jest.config.js
  scheduler_jupyter_plugin/tests/__init__.py
  setup.py
  src/__tests__/scheduler_jupyter_plugin.spec.ts
  src/controls/DynamicDropdown.tsx
  src/controls/RegionDropdown.tsx
  src/controls/SchedulerWidget.tsx
  src/services/LoggingService.ts
  style/index.js
  ui-tests/jupyter_server_test_config.py
  ui-tests/playwright.config.js
  ui-tests/tests/scheduler_jupyter_plugin.spec.ts
Labels: enhancement

#53 Added license in a file
  src/utils/ListRuntimeTemplateInterface.ts
Labels: enhancement
